# Generated by Django 3.2.5 on 2021-08-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karma_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
