# Generated by Django 3.2.5 on 2021-08-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karma_panel', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50, unique=True)),
                ('productimg', models.ImageField(upload_to='E:\\djangoproject\\env_swan\\karmaapp\\media/')),
                ('brand', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField()),
                ('Description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category_dtls',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=1234)),
                ('firstname', models.CharField(max_length=100)),
                ('contactno', models.BigIntegerField(null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.CharField(default='quantity', max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma_panel.add_product')),
            ],
        ),
        migrations.AddField(
            model_name='add_product',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='karma_panel.category_dtls'),
        ),
    ]
