# Generated by Django 3.2.5 on 2021-08-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karma_panel', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
