# Generated by Django 3.2.5 on 2021-08-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karma_panel', '0004_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_dtls',
            old_name='id',
            new_name='cid',
        ),
    ]
