# Generated by Django 3.2.5 on 2021-08-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karma_panel', '0005_rename_id_category_dtls_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma_panel.category_dtls'),
        ),
    ]
