# Generated by Django 3.2.5 on 2021-09-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karma_panel', '0006_alter_add_product_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='cat_id',
        ),
    ]
