# Generated by Django 3.2.5 on 2021-09-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma_panel', '0007_remove_add_product_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='productimg',
            field=models.ImageField(upload_to='E:\\djangoproject/'),
        ),
    ]
