# Generated by Django 3.2.5 on 2021-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma_panel', '0008_alter_add_product_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='productimg',
            field=models.ImageField(upload_to='E:/djangoproject/env_swan/karmaapp/media/'),
        ),
    ]
