# Generated by Django 3.2.5 on 2021-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma_panel', '0010_auto_20210917_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactno',
            field=models.IntegerField(null=True),
        ),
    ]
